name: Count INO Files
on: [push]

jobs:
  count-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count .ino files
        run: |
          count=$(find . -name "*.ino" | wc -l)
          echo "Number of .ino files in the repository: $count"
